version: '3'  # version of compose format

services:
  reservation:
    build: ./reservation
    volumes:
      - ./db.sqlite3:/db.sqlite3
      - ./reservation:/reservation
    ports:
      - 8082:8082
  score:
    build: ./score
